name: Deploy the websocket

on:
    push:
        branches: [ main ]

jobs:
    build:
        name: Deploying monorepo
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code # this will copy all files from github repo and paste in virtual machine
              uses: actions/checkout@v2

            - name: Docker login # login docker
              uses: docker/login-action@v2
              with: 
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Build and push # build image using my Dockerfile and then push
              uses: docker/build-push-action@v4
              with: 
                context: .
                file: ./docker/Dockerfile.ws
                push: true
                tags: karnaman02/todo-app-websocket:${{ github.sha }}
